version: '3.9'

services:
  eventex:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./eventex:/eventex
      - ./data/web:/vol/web
    environment:
    - SECRET_KEY=devsecretkey
    - DEBUG=1
    - DB_HOST=db
    - DB_NAME=devdb
    - DB_USER=devuser
    - DB_PASS=changeme
    - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
    - EMAIL_HOST=localhost
    - EMAIL_PORT=25
    - EMAIL_USE_TLS=0
    - EMAIL_HOST_USER=
    - EMAIL_HOST_PASSWORD=
    depends_on:
    - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme